-- 코드를 입력하세요
SELECT
    C.CAR_ID AS CAR_ID,
    C.CAR_TYPE AS CAR_TYPE,
    FLOOR(C.DAILY_FEE*(1-DP.DISCOUNT_RATE/100)*30)AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR C
JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
ON
    C.CAR_TYPE = DP.CAR_TYPE
LEFT JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON
    C.CAR_ID = H.CAR_ID
WHERE
    C.CAR_ID NOT IN(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE>='2022-11-01'AND START_DATE<='2022-11-30')
    AND DP.DURATION_TYPE LIKE '30%'
    AND C.CAR_TYPE IN('세단','SUV')
    AND ROUND(C.DAILY_FEE * 30 *(100-DP.DISCOUNT_RATE)/100) BETWEEN 500000 AND 2000000
GROUP BY
    C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, DP.DISCOUNT_RATE
ORDER BY
    FEE DESC,
    C.CAR_TYPE ASC,
    C.CAR_ID DESC;