-- 코드를 입력하세요
WITH FOOD_MAX_FAVORITES AS (
    SELECT
        FOOD_TYPE,
        MAX(FAVORITES) AS MAX_FAVORITES
    FROM
        REST_INFO
    GROUP BY
        FOOD_TYPE
)
SELECT
    R.FOOD_TYPE,
    R.REST_ID,
    R.REST_NAME,
    R.FAVORITES
FROM
    REST_INFO R
JOIN
    FOOD_MAX_FAVORITES F
ON
    R.FOOD_TYPE = F.FOOD_TYPE AND R.FAVORITES = F.MAX_FAVORITES
ORDER BY
    R.FOOD_TYPE DESC;