SELECT
    h.HISTORY_ID,
    FLOOR(
        c.DAILY_FEE * 
        CASE
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 90 THEN (DATEDIFF(h.END_DATE, h.START_DATE) + 1) * (1 - dp.DISCOUNT_RATE / 100)
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 30 THEN (DATEDIFF(h.END_DATE, h.START_DATE) + 1) * (1 - dp.DISCOUNT_RATE / 100)
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 7 THEN (DATEDIFF(h.END_DATE, h.START_DATE) + 1) * (1 - dp.DISCOUNT_RATE / 100)
            ELSE DATEDIFF(h.END_DATE, h.START_DATE) + 1
        END
    ) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR c
JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY h
ON
    c.CAR_ID = h.CAR_ID
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp
ON
    c.CAR_TYPE = dp.CAR_TYPE AND
    (
        (dp.DURATION_TYPE = '7일 이상' AND DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 7 AND DATEDIFF(h.END_DATE, h.START_DATE) + 1 < 30) OR
        (dp.DURATION_TYPE = '30일 이상' AND DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 30 AND DATEDIFF(h.END_DATE, h.START_DATE) + 1 < 90) OR
        (dp.DURATION_TYPE = '90일 이상' AND DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 90)
    )
WHERE
    c.CAR_TYPE = '트럭'
ORDER BY
    FEE DESC,
    h.HISTORY_ID DESC;
