-- 코드를 입력하세요
SELECT
    A.APNT_NO AS APNTNO,
    P.PT_NAME AS PTNAME,
    A.PT_NO AS PTNO,
    A.MCDP_CD AS MCDPCD,
    D.DR_NAME AS DRNAME,
    A.APNT_YMD AS APNTYMD
FROM
    APPOINTMENT A
JOIN
    PATIENT P ON A.PT_NO = P.PT_NO
JOIN
    DOCTOR D ON A.MDDR_ID = D.DR_ID
WHERE
    DATE(A.APNT_YMD) = '2022-04-13'
    AND A.APNT_CNCL_YN = 'N'
    AND A.MCDP_CD = 'CS'
ORDER BY
    A.APNT_YMD;