SELECT
    e.ID,
    e.GENOTYPE,
    p.GENOTYPE AS PARENT_GENOTYPE
FROM
    ECOLI_DATA e
JOIN
    ECOLI_DATA p
ON
    e.PARENT_ID = p.ID
WHERE
    (e.GENOTYPE | p.GENOTYPE) = e.GENOTYPE
ORDER BY
    e.ID ASC;