-- 코드를 입력하세요
WITH CAR_TOTAL_RENTALS AS (
    SELECT
        CAR_ID,
        COUNT(*) AS TOTAL_RENTALS
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY
        CAR_ID
    HAVING
        COUNT(*)>=5
),
CAR_MONTHLY_RENTALS AS (

    SELECT
        DATE_FORMAT(START_DATE, '%m') AS MONTH,
        CAR_ID,
        COUNT(*) AS RECORDS
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY
        DATE_FORMAT(START_DATE, '%Y-%m'), CAR_ID
)
SELECT
    CAST(MONTH AS UNSIGNED) AS MONTH,
    CAR_ID,
    RECORDS
FROM
    CAR_MONTHLY_RENTALS
WHERE
    CAR_ID IN (SELECT CAR_ID FROM CAR_TOTAL_RENTALS)
ORDER BY
    MONTH ASC,
    CAR_ID DESC;
