WITH YearMax AS (
    SELECT EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS year, MAX(SIZE_OF_COLONY) AS max_size
    FROM ECOLI_DATA
    GROUP BY EXTRACT(YEAR FROM DIFFERENTIATION_DATE)
)
SELECT EXTRACT(YEAR FROM e.DIFFERENTIATION_DATE) AS year,
       (y.max_size - e.SIZE_OF_COLONY) AS YEAR_DEV,
       e.ID
FROM ECOLI_DATA e
JOIN YearMax y
    ON EXTRACT(YEAR FROM e.DIFFERENTIATION_DATE) = y.year
ORDER BY year ASC, YEAR_DEV ASC;
