-- 코드를 작성해주세요
WITH FISH_ADJUSTED AS(

    SELECT
        FISH_TYPE,
        COALESCE(LENGTH, 10) AS LENGTH
    FROM
        FISH_INFO
),
FISH_STATS AS (
    SELECT
        FISH_TYPE,
        AVG(LENGTH) AS AVG_LENGTH,
        COUNT(*) AS FISH_COUNT,
        MAX(LENGTH) AS MAX_LENGTH
    FROM
        FISH_ADJUSTED
    GROUP BY
        FISH_TYPE

)
SELECT
    FISH_COUNT,
    MAX_LENGTH,
    FISH_TYPE
FROM
    FISH_STATS
WHERE
    AVG_LENGTH>=33
ORDER BY
    FISH_TYPE ASC;