WITH 
FE AS (
    SELECT BIT_OR(CODE) AS FE_CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
PY AS (
    SELECT CODE AS PY_CODE
    FROM SKILLCODES
    WHERE NAME = 'Python' AND CATEGORY = 'Back End'
),
CS AS (
    SELECT CODE AS CS_CODE
    FROM SKILLCODES
    WHERE NAME = 'C#' AND CATEGORY = 'Back End'
),
DEV_GRADE AS (
    SELECT
        CASE
            WHEN (D.SKILL_CODE & FE.FE_CODE) > 0 
                 AND (D.SKILL_CODE & PY.PY_CODE) > 0 THEN 'A'
            WHEN (D.SKILL_CODE & CS.CS_CODE) > 0 THEN 'B'
            WHEN (D.SKILL_CODE & FE.FE_CODE) > 0 THEN 'C'
            ELSE NULL
        END AS GRADE,
        D.ID,
        D.EMAIL
    FROM DEVELOPERS D
    CROSS JOIN FE
    CROSS JOIN PY
    CROSS JOIN CS
)

SELECT GRADE, ID, EMAIL
FROM DEV_GRADE
WHERE GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC;
